services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
    depends_on:
      - mongo
      - rabbitmq

  worker:
    build: ./worker
    depends_on:
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server --address ":9000" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
