version: "3.8"

services:
  api:
    build: ../api
    ports:
      - "3001:3001"
    env_file:
      - ../api/.env
    depends_on:
      - mongo
      - rabbitmq

  worker:
    build: ../worker
    depends_on:
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
